### ISSUE TITLE
TypeError: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by crilleaz** [Zecuel/NewsBot#1]
TypeError: Cannot read property 'children' of undefined
    at rp.then (/home/auto/program/scrapers.js:92:78)
    at tryCatcher (/home/auto/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/auto/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/auto/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/home/auto/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/auto/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/home/auto/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/auto/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/auto/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/home/auto/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

Any fix for this?

**Comment by Zecuel** [comment]
Hi! The NewsBot is currently not being maintained as I'm currently serving in the defence forces. This error is caused by the scrapers not being updated though. The structure of newsposts seems to change every once in a while, and the scrapers need to be updatef accordingly. All you'd need to change is the scraper's logic to match the new structures of news posts.
